language: ruby

script:
 - rspec
 - gem build fr_scaffold.gemspec
 - gem install fr_scaffold-0.0.3.gem
 - fr_scaffold --help
 - fr_scaffold --version

rvm:
  - 2.0.0
  - 1.9.3
  #- jruby
  #- rbx

gemfile:
  - Gemfile
